name: Run Tests

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.22' ]
    name: Go ${{ matrix.version }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/checkout@v4
      # Install ginkgo
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - run: go vet ./...
      - run: ginkgo -r -randomize-all -randomize-suites -race -trace -procs=2 -poll-progress-after=10s -poll-progress-interval=10s